export const orders = [
  {
    customer: "Eren Jaegar",
    image: "/path/to/image3",
    menu: "Spicy seasoned seafood noodles",
    payment: 125,
    status: "Completed",
  },
  {
    customer: "Mikasa Ackerman",
    image: "/path/to/image1",
    menu: "Grilled chicken with salad",
    payment: 150,
    status: "Preparing",
  },
  {
    customer: "Armin Arlert",
    image: "/path/to/image2",
    menu: "Vegetarian pasta",
    payment: 100,
    status: "Pending",
  },
  {
    customer: "Levi Ackerman",
    image: "/path/to/image3",
    menu: "Beef steak with fries",
    payment: 200,
    status: "Completed",
  },
  {
    customer: "Sasha Blouse",
    image: "/path/to/image4",
    menu: "Potato soup",
    payment: 80,
    status: "Preparing",
  },
  {
    customer: "Jean Kirstein",
    image: "/path/to/image5",
    menu: "Fish and chips",
    payment: 120,
    status: "Completed",
  },
  {
    customer: "Connie Springer",
    image: "/path/to/image6",
    menu: "Spicy ramen",
    payment: 90,
    status: "Pending",
  },
  {
    customer: "Historia Reiss",
    image: "/path/to/image7",
    menu: "Chicken curry",
    payment: 110,
    status: "Preparing",
  },
  {
    customer: "Hange Zoë",
    image: "/path/to/image8",
    menu: "Vegan burger",
    payment: 130,
    status: "Completed",
  },
  {
    customer: "Erwin Smith",
    image: "/path/to/image9",
    menu: "Pork ribs",
    payment: 180,
    status: "Completed",
  },
];
